version: 2.1

jobs:
  works-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world"                  # Install dependencies
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - works-job
