version: 2.1

jobs:
  works-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world" 
      - run: ls -la
      - run: npm install
      - run: npm run                
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - works-job
