version: 2.1

jobs:
  works-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world"
      - run: node  home/SoftEngGroup/.circleci/index.mjs

workflows:
  my-workflow:
    jobs:
      - works-job
