version: 2.1

jobs:
  works-job:
    working_directory: ~/src
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world" 
      - run: npm install           
      - run: npm test

workflows:
  my-workflow:
    jobs:
      - works-job
